project:
  type: website
  
execute:
  freeze: auto

website:
  title: "quarto-course-website"
  navbar:
    right:
      - text: "Join"
        file: join.qmd
      - text: "Prerequisites"
        file: prerequisites.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Content"
        file: content.qmd
 
      - icon: github
        href: https://github.com/Warwick-Stats-Resources/quarto-course-website
format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    link-external-newwindow: true



